workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - your@email.com
